site_name: Hyper Protect Virtual Servers (HPVS) Hosted Trial
repo_url: https://github.com/ibm-hyper-protect/hyper-protect-virtual-servers-hosted-trial/
edit_uri: edit/master/docs
nav:
    - Home: index.md
    - Prerequisites: prerequisites.md
    - Setting up the environment: setting_upenv.md
    - Explore the Hyper Protect Virtual Servers CLI: setenv.md
    - Secure Build Server (SBS):
      - Hyper Protect Virtual Servers (HPVS) Secure Build overview: securebuild/overview.md
      - Enabling ports: securebuild/sbs-ports-setup.md
      - Creating the Secure Build Server: securebuild/create-server-hpvsdeploy.md
      - Securely Build your Application: securebuild/build.md
      - Deploy your Securely Built Application as a Hyper Protect Virtual Server: securebuild/deploy-app.md
      - Welcome to the Digital Banking Application: securebuild/digital_banking.md
      - Clean up your Environment: securebuild/cleanup.md
    - Bring your own image (BYOI):
      - Bring your own image overview: byoi/overview_byoi.md
      - Deploying your applications securely: byoi/byoi.md
      - Generating signing keys: byoi/gen_sign_key.md
    - GREP11:
      - IBM Hyper Protect Virtual Servers GREP11 Overview: grep11/overview.md
      - How to set up a GREP11 server: grep11/grep11-setup.md
      - Displaying your GREP11 environment: grep11/grep11-display.md
      - Running the GREP11 sample code: grep11/run-grep11-samples.md
      - Running the sample exercises:
        - An overview of the Exercises: grep11/exercise-overview.md
        - Exercise 1 (List PKCS Mechanisms): grep11/lab-exercise1.md
        - Exercise 2 (Encryption and Decryption): grep11/lab-exercise2.md
        - Exercise 3 (Sign and Verify): grep11/lab-exercise3.md
        - Exercise 4 (Wrap and Unwrap Key): grep11/lab-exercise4.md
    - Reference:
      - Undeploying virtual servers: reference/hpvs_undeploy.md
      - Updating virtual servers: reference/hpvs_update.md
    - Glossary of terms: glossary.md
    - Other resources: resources.md

theme:
  name: material
  palette:
    scheme: preference
  favicon: images/hpvs-logo.svg
  logo: images/hpvs-logo.svg
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm-wsc
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/s390x
google_analytics:
  - UA-174658170-2
  - auto
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - attr_list
  - toc:
      permalink: true
