site_name: Hyper Protect Virtual Servers (HPVS) Hosted Trial
repo_url:  https://ibm-hyper-protect.github.io/hyper-protect-virtual-servers-hosted-trial
edit_uri: edit/master/docs
nav:
    - Home: index.md
    - Prerequisites: prerequisites.md
    #- Lab Assignments: assignment.md
    - Secure Build:
      - Hyper Protect Virtual Servers (HPVS) Lab Process Overview: securebuild/overview.md
      - Configuring your Environment: securebuild/securebuild-setup.md
      - Create your HPVS Secure Build Server by using the hpvs vs create command: securebuild/create-server.md
      - Create your HPVS Secure Build Server by using the yaml configuration file and `hpvs deploy` command: securebuild/create-server-hpvsdeploy.md
      - Securely Build your Application: securebuild/build.md
      - Deploy your Securely Built Application as a Hyper Protect Virtual Server: securebuild/deploy-app.md
    #  - Welcome to the Secure Bitcoin Wallet on IBM LinuxONE: securebuild-lab/bitcoin_wallet.md
      - Clean up your Environment: securebuild/cleanup.md
    - BYOI:
      - Overview: byoi/overview_byoi.md
      - Generating signing keys: byoi/gen_sign_key.md
      - Bring your own image: byoi/byoi.md
    - GREP11:
      - Lab overview: grep11/overview.md
      - How to set up a GREP11 server: grep11/grep11-setup.md
      - Displaying your GREP11 environment: grep11/grep11-display.md
    - Reference:
      - Undeploying virtual servers: reference/hpvs_undeploy.md
      #- Run the GREP11 sample code: grep11-lab/run-grep11-samples.md
      #- Run the Lab exercises:
      #  - An overview of the Exercises: grep11-lab/exercise-overview.md
      #  - Exercise 1 (List PKCS Mechanisms): grep11-lab/lab-exercise1.md
      #  - Exercise 2 (Encryption and Decryption): grep11-lab/lab-exercise2.md
      #  - Exercise 3 (Sign and Verify): grep11-lab/lab-exercise3.md
      #  - Exercise 4 (Wrap and Unwrap Key): grep11-lab/lab-exercise4.md
    - Glossary of terms: glossary.md
    - Other resources: resources.md
    - Propose a change: proposechange.md

theme:
  name: gitbook
  palette:
    scheme: preference
  favicon: images/hpvs-logo.svg
  logo: images/hpvs-logo.svg
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm-wsc
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/s390x
google_analytics:
  - UA-174658170-2
  - auto
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - attr_list
  - toc:
      permalink: true
